### PR TITLE
Add lifecycle events for hiding / showing views before / after nav transitions

### PR DESCRIPTION
**Pull request by programmarchy**
Found myself wanting predictable lifecycle events in my views, rather than sprinkling code into onComplete callbacks e.g. kicking off animations. The `componentDidMount` event is often not appropriate to initiate certain things on the view since it's still animating the transition at that point.

Added the following lifecycle events:

`navigationControllerWillHideView`
`navigationControllerWillShowView`
`navigationControllerDidHideView`
`navigationControllerDidShowView`

### CODE REVIEW

**Comment by aputinski** [comment]
@programmarchy Thanks for the PR — would you mind merging master (I fixed an issue that was causing tests to not run) and then add a few tests?

**Comment by programmarchy** [comment]
Ok, merged in upstream master and writing some tests.

I'm new to `karma` and running into a little trouble. Here's how I'm trying to test a lifecycle event:

```
    it('calls lifecycle events', (done) => {
      const didShowViewSpy = sinon.spy();
      const didHideViewSpy = sinon.spy();
      controller.__pushView(<ViewB />, {
        transition: Transition.type.NONE
      });
      controller.forceUpdate(() => {
        let prevView = controller.refs['view-0'];
        let nextView = controller.refs['view-1'];
        prevView.navigationControllerDidHideView = didHideViewSpy;
        nextView.navigationControllerDidShowView = didShowViewSpy;
        requestAnimationFrame(() => {
          expect(didHideViewSpy.calledOnce).to.be.true;
          expect(didShowViewSpy.calledOnce).to.be.true;
          done();
        });
      });
    });
```

I found that I had to call `forceUpdate` because the view refs are not set up until the `setState` callback in `__pushView`. This seems a little bit hacky, though. Is there a better way to do this?

**Comment by programmarchy** [comment]
Found a better way to test by stubbing `__transitionViews` and setting up the spies there. Will generalize this test case so it covers more cases than just `pushView`.

**Comment by aputinski** [comment]
This is looking great — would you mind adding some info about the lifecycle events in the README?

**Comment by programmarchy** [comment]
Ok, added a few tests and updated the README.

**Comment by aputinski** [comment]
@programmarchy Thanks again for the PR!

**Pull request merged**
